# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Latest Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Package the py file as exe
      id: tag
      run: |
        pyinstaller -F motd.py
        pyinstaller -F send.py
        pyinstaller -F scan.py
        pyinstaller -F scanall.py
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
    
    - name: Create script
      run: |
        cmd
        chcp 65001
        cd D:\a\tools\tools\dist\
        cd . >> .\OpenMe.bat
        echo "@echo off" >> .\OpenMe.bat
        echo "echo Type a program name here to run." >> .\OpenMe.bat
        echo "echo Such as scan, motd, send and scanall." >> .\OpenMe.bat
        echo "cmd" >> .\OpenMe.bat
        echo "@echo on" >> .\OpenMe.bat

    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: MCBEprotocolTools.zip
        path: ./
        directory: ./dist/
        
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.14
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: ./dist/MCBEprotocolTools.zip
