# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Latest Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Set build info
      id: build_info
      run: |
        echo "build_time=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        echo "tag_name=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        echo "commit_msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
      shell: bash
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Package the py file as exe
      id: tag
      run: |
        pyinstaller -F motd.py
        pyinstaller -F send.py
        pyinstaller -F scan.py
    
    - name: Create script
      run: |
        chcp 65001
        cd .\dist\
        cd . >> .\OpenMe.bat
        echo "@echo off" >> .\OpenMe.bat
        echo "echo Type a program name here to run." >> .\OpenMe.bat
        echo "echo Such as scan, motd and send." >> .\OpenMe.bat
        echo "echo " >> .\OpenMe.bat
        echo "cmd" >> .\OpenMe.bat
        echo "@echo on" >> .\OpenMe.bat
      shell: cmd

    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: MCBEprotocolTools.zip
        path: ./
        directory: ./dist/
        
    - name: Release
      uses: softprops/action-gh-release@v0.1.14
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ steps.build_info.outputs.commit_msg }}
        tag_name: ${{ steps.build_info.outputs.tag_name }}
        body: "Build time: ${{ steps.build_info.outputs.build_time }}"
        files: ./dist/MCBEprotocolTools.zip
